version: '2'
services:
  main:
    environment:
        - DISPLAY
    privileged: true
    image: "pinfake/android-emulator-x11"
    volumes:
        - "/usr/lib:/hostlib/usr/lib"
        - "/tmp/.X11-unix:/tmp/.X11-unix" 
    ports: 
      - "0.0.0.0:5037:5037"
      - "0.0.0.0:5554:5554"
      - "0.0.0.0:5555:5555"
